# Generated by Django 5.1 on 2024-08-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
