# Generated by Django 5.1 on 2024-08-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0002_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='testomodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='userprof.colour'),
        ),
    ]
